name: "Papiro deploy"
description: "Publish markdown documents as a website."
author: "akrck02"
inputs:
  path:
    description: "documents directory"
    default: "docs"
  isObsidianProject:
    description: "docs use obsidian formats"
    default: "false"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
