name: "Papiro deploy"
description: "Publish markdown documents as a website."
author: "akrck02"
branding:
  color: white
  icon: file-text
inputs:
  title:
    description: "title"
    default: ""
  description:
    description: "description"
    default: ""
  logo:
    description: "logo"
    default: ""
  path:
    description: "documents directory"
    default: "docs"
  isObsidianProject:
    description: "docs use obsidian formats"
    default: "false"
  showFooter:
    description: "show the credits footer"
    default: "true"
  showBreadcrumb:
    description: "show the breadcrumb"
    default: "true"
  showStartPage:
    description: "show the start page"
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.24.3" # The Go version to download (if necessary) and use.

    - name: Prepare the papiro deploy
      id: papiro-deploy
      run: go run src/main.go
      shell: bash

    - name: Deploy to github actions 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
